spring:
  application:
      name: Spring Boot Task Scheduling
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jooq:
    sql-dialect: MYSQL
flyway:
  baseline-on-migrate: true