/*
 * This file is generated by jOOQ.
*/
package com.springboot.jooq;


import com.springboot.jooq.tables.FlywaySchemaHistory;
import com.springboot.jooq.tables.Task;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedule extends SchemaImpl {

    private static final long serialVersionUID = -1952106229;

    /**
     * The reference instance of <code>schedule</code>
     */
    public static final Schedule SCHEDULE = new Schedule();

    /**
     * The table <code>schedule.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.springboot.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>schedule.task</code>.
     */
    public final Task TASK = com.springboot.jooq.tables.Task.TASK;

    /**
     * No further instances allowed
     */
    private Schedule() {
        super("schedule", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Task.TASK);
    }
}
