/*
 * This file is generated by jOOQ.
*/
package com.springboot.jooq;


import com.springboot.jooq.tables.FlywaySchemaHistory;
import com.springboot.jooq.tables.Task;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in schedule
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>schedule.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.springboot.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>schedule.task</code>.
     */
    public static final Task TASK = com.springboot.jooq.tables.Task.TASK;
}
