/*
 * This file is generated by jOOQ.
*/
package com.springboot.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = -119551661;

    private UInteger  id;
    private String    name;
    private Boolean   executed;
    private Timestamp executedTime;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.name = value.name;
        this.executed = value.executed;
        this.executedTime = value.executedTime;
    }

    public Task(
        UInteger  id,
        String    name,
        Boolean   executed,
        Timestamp executedTime
    ) {
        this.id = id;
        this.name = name;
        this.executed = executed;
        this.executedTime = executedTime;
    }

    @NotNull
    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getExecuted() {
        return this.executed;
    }

    public void setExecuted(Boolean executed) {
        this.executed = executed;
    }

    public Timestamp getExecutedTime() {
        return this.executedTime;
    }

    public void setExecutedTime(Timestamp executedTime) {
        this.executedTime = executedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(executed);
        sb.append(", ").append(executedTime);

        sb.append(")");
        return sb.toString();
    }
}
